FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.9.2@sha256:8a5227733cec9506389cadccbdd54eaf50dbdfd86fbc49c78309741c70bd358c
MAINTAINER jiubian
