FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.10.2@sha256:5dd86b80f80b087fe0536870554635d7d80485e50ba310985e631bedfefd44a3
MAINTAINER jiubian
